packages:
  - "unit"
  - "apps/*"
  # - "e2e"
  # - "e2e/examples/*"  # disabled: references missing vectorstores package
  - "packages/*"
  - "packages/providers/*"
  - "packages/providers/storage/*"
  - "packages/providers/retriever/*"
  - "packages/core/tests"
  - "packages/node-parser/tests"
  - "packages/readers/tests"
  - "packages/env/tests"
  - "examples/"
  - "examples/**"
