packages:
  - "unit"
  - "apps/*"
  - "e2e"
  - "e2e/examples/*"
  - "packages/*"
  - "packages/providers/*"
  - "packages/providers/storage/*"
  - "packages/providers/retriever/*"
  - "packages/core/tests"
  - "packages/llamaindex/tests"
  - "examples/"
  - "examples/**"
